### ISSUE TITLE
Category image is missing in category feed. 

### ISSUE THREAD

**Issue by ghost** [headout/api-docs#11]
Hi Team,
Please add the image details in the category feed.

  {
      "id": 324,
      "name": "Lifestyle & Entertainment",
      "cityCode": "DUBAI",
      "url": "/category/324/dubai-lifestyle-and-entertainment",
      "canonicalUrl": "https://www.headout.com/category/324/dubai-lifestyle-and-entertainment"
    },

**Comment by kunal15595** [comment]
https://www.headout.com/api/public/v1/category/list-by/city?cityCode=dubai
category listing api contains image
