### ISSUE TITLE
City List Issue

### ISSUE THREAD

**Issue by Jayesh26121988** [headout/api-docs#8]
Give me APi format or an example for get CityList

**Comment by kunal15595** [comment]
Hi Jayesh
Currently, there is no API for listing cities. We'll be adding this very soon (within a week), after which you can find the details in the api docs

**Comment by Jayesh26121988** [comment]
Thank you for your reply.

So, How can we go ahead with this API?

**Comment by kunal15595** [comment]
The API covers 3 broad topics:
1. Product
2. Inventory
3. Booking
You can find these here - https://github.com/headout/api-docs#apis

**Comment by kunal15595** [comment]
Hi Jayesh
We have added city-listing, category-listing & category-product-listing APIs.
Please find the details in the docs.

**Comment by Jayesh26121988** [comment]
Hi Krunal

I check api but its not working pls give me example how can i get city list.

**Comment by Jayesh26121988** [comment]
![citylist](https://user-images.githubusercontent.com/41152505/44511739-1cba8c80-a6d6-11e8-9f52-d8af4eb94749.PNG)

**Comment by kunal15595** [comment]
This is the correct URL - https://www.headout.com/api/public/v1/city?offset=0&limit=30
query params are to be separated by `&` and not `,`

**Comment by Jayesh26121988** [comment]
ok done thank you krunal

**Comment by kunal15595** [comment]
Resolved. closing.

**Comment by Jayesh26121988** [comment]
Hi Kunal

How to get product option price this api. 

https://www.headout.com/api/v1/product/get/1866

In response I don't get product option price.

This are the options.
1)Burj Khalifa + Dubai Fountain Boardwalk
2)Sunrise + Pastry & Coffee at The Café
3)General Admission
4)Burj Khalifa + Pastry & Coffee at The Café
5)Burj Khalifa + Dubai Aquarium & Underwater Zoo
6)Burj Khalifa Fast Track Access
7)Burj Khalifa At the Top Sky (Level 124, 125 & 148)

FYR.Attach Json Response for this activity

[headout response.txt](https://github.com/headout/api-docs/files/2404825/headout.response.txt)

**Comment by Jayesh26121988** [comment]
Hi Kunal

Headout supplier, when i search record. In api can i passed fromdate,noofadult,noofchild wise get perperson price. 

https://www.headout.com/api/v1/product/listing/list-by/city?cityCode=LONDON&currencyCode=AED&fromdate='13/07/2018 12:00:00 AM'&todate='19/07/2018 12:00:00 AM'

**Comment by Jayesh26121988** [comment]
![minimumprice](https://user-images.githubusercontent.com/41152505/45879910-d125fc00-bdc3-11e8-8dde-b747982c27e2.png)
![variants](https://user-images.githubusercontent.com/41152505/45879911-d125fc00-bdc3-11e8-9d10-258a2084ca13.png)

in Response i got 3 options.how to get options price.

**Comment by Jayesh26121988** [comment]
Hi kunal,


https://www.headout.com/api/v1/product/get/593

This Api Not comes this product which category to mapped.

**Comment by Jayesh26121988** [comment]
![single product](https://user-images.githubusercontent.com/41152505/45881749-c1111b00-bdc9-11e8-9460-e58616164a63.png)

**Comment by Jayesh26121988** [comment]
https://www.headout.com/api/v1/product/get/3353

in this api can i get aed currency price


https://www.headout.com/api/v1/product/get/3353?currencyCode=AED

I passed but it's gives GBP currency format.

"currency": {
        "code": "GBP",
